/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhony The Beste
 */
public class Administrador extends javax.swing.JFrame {
    String user,nombre_usuario="";
    public static int sesion_usuario;

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        user=Login.user;
        sesion_usuario=1;
        
        setSize(1200,900);
         setResizable(false);
        
        setTitle("Administrador - sesion "+user);
       setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
        
         ImageIcon wallpaper = new ImageIcon("src/mages/wallpaperPrincipal.jpg");
        Icon icono =new ImageIcon(wallpaper.getImage().getScaledInstance(lb_img.getWidth(),
                lb_img.getHeight(),Image.SCALE_DEFAULT));
       lb_img.setIcon(icono);
       lb_img.repaint();
        
        try{
              Connection cn= Conexion.conectar();
               PreparedStatement pst = cn.prepareStatement(
              "select nombre_usuario from usuarios where username= '" +user+"'");
               
               ResultSet rs=pst.executeQuery();
               if(rs.next()){
                   nombre_usuario=rs.getString("nombre_usuario");
                   mostrar_nombre.setText(nombre_usuario);
                   System.out.println(nombre_usuario);
                   
               }
        }catch(Exception e){
            System.err.println("error en la conexion desde el Administrador");
        }
    }
    @Override
public Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("mages/icon.png"));
    return retValue;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre_user = new javax.swing.JLabel();
        registrar_usuario = new javax.swing.JButton();
        gescionar_usuario = new javax.swing.JButton();
        tecnico = new javax.swing.JButton();
        capturista = new javax.swing.JButton();
        acerca_de = new javax.swing.JButton();
        creatividad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        mostrar_nombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lb_img = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombre_user.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_nombre_user.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label_nombre_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        registrar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/addUser.png"))); // NOI18N
        registrar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(registrar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 100));

        gescionar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/informationuser.png"))); // NOI18N
        gescionar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gescionar_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(gescionar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 130, 100));

        tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/tecnico.png"))); // NOI18N
        tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 130, 90));

        capturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/capturista.png"))); // NOI18N
        capturista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturistaActionPerformed(evt);
            }
        });
        getContentPane().add(capturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 120, 90));

        acerca_de.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/geekipedia.png"))); // NOI18N
        acerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acerca_deActionPerformed(evt);
            }
        });
        getContentPane().add(acerca_de, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, 130, 90));

        creatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/creatividad.png"))); // NOI18N
        creatividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatividadActionPerformed(evt);
            }
        });
        getContentPane().add(creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 130, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gescionar vendedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar productos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 370, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar productos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Detalle de venta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 360, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrar vendedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("creada por yvon voyelle ");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 210, -1));

        mostrar_nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mostrar_nombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(mostrar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 210, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ingresar Cliente con credito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Actualizar Cliente con credito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Informacion cliente con deuda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 400, -1));

        lb_img.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lb_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1200, 690));
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void gescionar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gescionar_usuarioActionPerformed


        GestionarUsuarios gestionar_usuarios=new GestionarUsuarios();
       gestionar_usuarios.setVisible(true);
    }//GEN-LAST:event_gescionar_usuarioActionPerformed

    private void tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnicoActionPerformed
        Editar editar = new Editar() ;
        editar.setVisible(true);
    }//GEN-LAST:event_tecnicoActionPerformed

    private void registrar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_usuarioActionPerformed
RegistroUsuarios registrarUs= new RegistroUsuarios();
 
registrarUs.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_registrar_usuarioActionPerformed

    private void creatividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatividadActionPerformed
Agregar producto= new Agregar();
producto.setVisible(true);        
    }//GEN-LAST:event_creatividadActionPerformed

    private void capturistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturistaActionPerformed
    Eliminar eliminar = new Eliminar();
    eliminar.setVisible(true);
    }//GEN-LAST:event_capturistaActionPerformed

    private void acerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acerca_deActionPerformed
      
   TablaVentas ventas=new TablaVentas();
   ventas.setVisible(true);
     
    }//GEN-LAST:event_acerca_deActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Cliente_con_credito cliente=new Cliente_con_credito();
       cliente.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     EditarCliente cliente=new EditarCliente ();
       cliente.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Deuda deuda= new Deuda();
        deuda.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acerca_de;
    private javax.swing.JButton capturista;
    private javax.swing.JButton creatividad;
    private javax.swing.JButton gescionar_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_nombre_user;
    private javax.swing.JLabel lb_img;
    private javax.swing.JLabel mostrar_nombre;
    private javax.swing.JButton registrar_usuario;
    private javax.swing.JButton tecnico;
    // End of variables declaration//GEN-END:variables
}
