
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Jhony The Beste
 */
public class Login extends javax.swing.JFrame {

   public static String user="";
   String pass="";
    
    
    public Login() {
        initComponents();
        
        setResizable(false);
        setSize(800,600);
        setTitle("Acceso al Systema");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/mages/wallpaperPrincipal.jpg");
        Icon icono =new ImageIcon(wallpaper.getImage().getScaledInstance(label_wall.getWidth(),
                label_wall.getHeight(),Image.SCALE_DEFAULT));
        label_wall.setIcon(icono);
        label_wall.repaint();
        
        ImageIcon wallpaper_logo =new ImageIcon("src/mages/DS.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(label_logo.getWidth(),label_logo.getHeight(),Image.SCALE_DEFAULT));
        label_logo.setIcon(icono_logo);
       label_logo.repaint();
       
    }
@Override
public Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("mages/icon.png"));
    return retValue;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_logo = new javax.swing.JLabel();
        text_user = new javax.swing.JTextField();
        text_pass = new javax.swing.JPasswordField();
        label_copi = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 550, 270));

        text_user.setBackground(new java.awt.Color(153, 153, 255));
        text_user.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_user.setForeground(new java.awt.Color(255, 255, 255));
        text_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_userActionPerformed(evt);
            }
        });
        getContentPane().add(text_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 305, 270, 60));

        text_pass.setBackground(new java.awt.Color(153, 153, 255));
        text_pass.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_pass.setForeground(new java.awt.Color(255, 255, 255));
        text_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passActionPerformed(evt);
            }
        });
        getContentPane().add(text_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 270, 60));

        label_copi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_copi.setText("Creada por yvon voyelle");
        getContentPane().add(label_copi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 270, 20));

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Acceder");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 150, -1));

        label_wall.setBackground(new java.awt.Color(102, 0, 0));
        label_wall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_wallMouseClicked(evt);
            }
        });
        label_wall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                label_wallKeyPressed(evt);
            }
        });
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 810, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void label_wallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_wallMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_wallMouseClicked

    private void text_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_userActionPerformed

    private void text_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passActionPerformed

    private void label_wallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_label_wallKeyPressed
 if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        user=text_user.getText();
      pass=text_pass.getText();
      
      if(!user.equals("")||!pass.equals("")){
          
          try{
              Connection cn= Conexion.conectar();
               PreparedStatement pst = cn.prepareStatement(
               "select tipo_nivel, estatus from usuarios where username = '" + user
                + "' and password = '" + pass + "'");
              
              ResultSet rs= pst.executeQuery();
              if(rs.next()){
                  String tipo_nivel =rs.getString("tipo_nivel");
                  String estatus =rs.getString("estatus");
                  
                  if(tipo_nivel.equalsIgnoreCase("Administrador") && estatus.equalsIgnoreCase("Activo")){
                      dispose();
                      new Administrador().setVisible(true);
                      
                  }else if(tipo_nivel.equalsIgnoreCase("Capturista") && estatus.equalsIgnoreCase("Activo")){
                          dispose();
                      new caja().setVisible(true);
                      
                  }else if(tipo_nivel.equalsIgnoreCase("Tecnico") && estatus.equalsIgnoreCase("Activo")){
                          dispose();
                      new Tecnico().setVisible(true);
                  
              }
                  
              }else{
               JOptionPane.showMessageDialog(null, "Datos de acceso incorrecto");  
              text_user.setText("");
              text_pass.setText("");
              }
              
         }catch(Exception e){
              System.err.println("error en boton "+e);
           JOptionPane.showMessageDialog(null, "error en acceder ,contactar con tu Aministrador");
      }
          
      }else{
          JOptionPane.showMessageDialog(null, "debe llenar dolos campos");
      }
 }// TODO add your handling code here:
    }//GEN-LAST:event_label_wallKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        user=text_user.getText();
      pass=text_pass.getText();
      
      if(!user.equals("")||!pass.equals("")){
          
          try{
              Connection cn= Conexion.conectar();
               PreparedStatement pst = cn.prepareStatement(
               "select tipo_nivel, estatus from usuarios where username = '" + user
                + "' and password = '" + pass + "'");
              
              ResultSet rs= pst.executeQuery();
              if(rs.next()){
                  String tipo_nivel =rs.getString("tipo_nivel");
                  String estatus =rs.getString("estatus");
                  
                  if(tipo_nivel.equalsIgnoreCase("Administrador") && estatus.equalsIgnoreCase("Activo")){
                      dispose();
                      new Administrador().setVisible(true);
                      
                  }else if(tipo_nivel.equalsIgnoreCase("Capturista") && estatus.equalsIgnoreCase("Activo")){
                          dispose();
                      new caja().setVisible(true);
                      
                  }else if(tipo_nivel.equalsIgnoreCase("Tecnico") && estatus.equalsIgnoreCase("Activo")){
                          dispose();
                      new Tecnico().setVisible(true);
                  
              }
                  
              }else{
               JOptionPane.showMessageDialog(null, "Datos de acceso incorrecto");  
              text_user.setText("");
              text_pass.setText("");
              }
              
         }catch(Exception e){
              System.err.println("error en boton "+e);
           JOptionPane.showMessageDialog(null, "error en acceder ,contactar con tu Aministrador");
      }
          
      }else{
          JOptionPane.showMessageDialog(null, "debe llenar dolos campos");
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel label_copi;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_wall;
    private javax.swing.JPasswordField text_pass;
    private javax.swing.JTextField text_user;
    // End of variables declaration//GEN-END:variables
}
